const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE'
const ADD_ITEM = 'ADD_ITEM'
const DELETE_ITEM = 'DELEtE_ITEM'

const GET_DATA = 'GET_DATA'

export {
  CHANGE_INPUT_VALUE,
  ADD_ITEM,
  DELETE_ITEM,
  GET_DATA
}